In [1]:
# import libraries
import tensorflow as tf
import numpy as np

print("TensorFlow Version:", tf.__version__)

TensorFlow Version: 2.18.0


## **Creating Tensors**

In [2]:
# create tensors
scalar = tf.constant(10)
vector = tf.constant([1, 5, 10, 13, 19])
matrix = tf.constant([[1, 6, 10], [4, 7, 13]])
tensor = tf.constant([[[11, 20], [34, 45]], [[61, 67], [99, 109]]])

# tensor properties
print("Scalar: ", scalar)
print("\nVector: ", vector)
print("\nMatrix: ", matrix)
print("\nTensor: ", tensor)

# shape and dtype
print("\nShapes and Data Types:\n")
print("Scalar shape:", scalar.shape, ", dtype:", scalar.dtype)
print("Vector shape:", vector.shape, ", dtype:", vector.dtype)
print("Matrix shape:", matrix.shape, ", dtype:", matrix.dtype)
print("Tensor shape:", tensor.shape, ", dtype:", tensor.dtype)

Scalar:  tf.Tensor(10, shape=(), dtype=int32)

Vector:  tf.Tensor([ 1  5 10 13 19], shape=(5,), dtype=int32)

Matrix:  tf.Tensor(
[[ 1  6 10]
 [ 4  7 13]], shape=(2, 3), dtype=int32)

Tensor:  tf.Tensor(
[[[ 11  20]
  [ 34  45]]

 [[ 61  67]
  [ 99 109]]], shape=(2, 2, 2), dtype=int32)

Shapes and Data Types:

Scalar shape: () , dtype: <dtype: 'int32'>
Vector shape: (5,) , dtype: <dtype: 'int32'>
Matrix shape: (2, 3) , dtype: <dtype: 'int32'>
Tensor shape: (2, 2, 2) , dtype: <dtype: 'int32'>


## **Basic Tensor Operations**

In [3]:
# tensor addition, subtraction, multiplication, and division
a = tf.constant([2, 4, 6])
b = tf.constant([1, 2, 3])

print("Addition:", tf.add(a, b).numpy())
print("Subtraction:", tf.subtract(a, b).numpy())
print("Multiplication:", tf.multiply(a, b).numpy())
print("Division:", tf.divide(a, b).numpy())

Addition: [3 6 9]
Subtraction: [1 2 3]
Multiplication: [ 2  8 18]
Division: [2. 2. 2.]


## **Reshaping and Transposing**

In [4]:
# reshaping tensors
tensor = tf.constant([[1, 2, 3], [4, 5, 6]])
reshaped_tensor = tf.reshape(tensor, (3, 2))

print("Original Tensor:\n", tensor.numpy())
print("Reshaped Tensor:\n", reshaped_tensor.numpy())

# transposing tensors
transposed_tensor = tf.transpose(tensor)
print("Transposed Tensor:\n", transposed_tensor.numpy())

Original Tensor:
 [[1 2 3]
 [4 5 6]]
Reshaped Tensor:
 [[1 2]
 [3 4]
 [5 6]]
Transposed Tensor:
 [[1 4]
 [2 5]
 [3 6]]


## **Dot Product and Matrix Multiplication**

In [5]:
# dot product (1D tensors)
x = tf.constant([1, 2, 3])
y = tf.constant([4, 5, 6])
dot_product = tf.tensordot(x, y, axes=1)

print("Dot Product:", dot_product.numpy())

# matrix multiplication
mat1 = tf.constant([[1, 2], [3, 4]])
mat2 = tf.constant([[5, 6], [7, 8]])
matmul_result = tf.matmul(mat1, mat2)

print("Matrix Multiplication Result:\n", matmul_result.numpy())

Dot Product: 32
Matrix Multiplication Result:
 [[19 22]
 [43 50]]


## **Broadcasting in TensorFlow**

In [6]:
# broadcasting Example
A = tf.constant([[1], [2], [3]])
B = tf.constant([1, 2, 3])
result = A + B

print("Broadcasting Example:\n", result.numpy())

Broadcasting Example:
 [[2 3 4]
 [3 4 5]
 [4 5 6]]


## **Einsum Operations**

In [7]:
# einsum examples
a = tf.random.uniform(shape=[3, 4])
b = tf.random.uniform(shape=[4, 5])

# matrix multiplication using einsum
einsum_matmul = tf.einsum('ij,jk->ik', a, b)

# trace of a square matrix
square_matrix = tf.constant([[1, 2], [3, 4]])
einsum_trace = tf.einsum('ii->', square_matrix)

# outer product
vector_1 = tf.constant([1, 2, 3])
vector_2 = tf.constant([4, 5, 6])
einsum_outer = tf.einsum('i,j->ij', vector_1, vector_2)

print("Einsum Matrix Multiplication Result:\n", einsum_matmul.numpy())
print("Einsum Trace of Matrix:\n", einsum_trace.numpy())
print("Einsum Outer Product:\n", einsum_outer.numpy())

Einsum Matrix Multiplication Result:
 [[1.3697671  2.4593422  1.3298445  1.8620478  1.1111609 ]
 [0.60312855 1.0497644  0.3391122  0.95724297 0.30616155]
 [0.8360146  1.5743948  1.1087475  1.0373797  0.9150677 ]]
Einsum Trace of Matrix:
 5
Einsum Outer Product:
 [[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]


## **Reduction Operations**

In [8]:
# sum, mean, max, min
tensor = tf.constant([[1, 2, 3], [4, 5, 6]])
print("Sum:", tf.reduce_sum(tensor).numpy())
print("Mean:", tf.reduce_mean(tensor).numpy())
print("Max:", tf.reduce_max(tensor).numpy())
print("Min:", tf.reduce_min(tensor).numpy())

# sum along axis
print("Sum along axis=0:", tf.reduce_sum(tensor, axis=0).numpy())
print("Sum along axis=1:", tf.reduce_sum(tensor, axis=1).numpy())

Sum: 21
Mean: 3
Max: 6
Min: 1
Sum along axis=0: [5 7 9]
Sum along axis=1: [ 6 15]


## **Gradient Computation with** *tf.GradientTape*

In [9]:
# tf.GradientTape for automatic differentiation
x = tf.Variable(3.0)

with tf.GradientTape() as tape:
    y = x**2 + 3*x + 5

# compute gradient dy/dx
dy_dx = tape.gradient(y, x)

print("Gradient dy/dx at x=3:", dy_dx.numpy())

Gradient dy/dx at x=3: 9.0
