In [1]:
# import libraries
import torch
import numpy as np
from einops import rearrange, reduce

print("PyTorch Version:", torch.__version__)

PyTorch Version: 2.5.1+cu124


## **Creating Tensors**

In [2]:
# Creating different types of tensors
scalar = torch.tensor(9)
vector = torch.tensor([11, 22, 33])
matrix = torch.tensor([[11, 12], [13, 14]])
tensor = torch.tensor([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

print("Scalar:", scalar)
print("Vector:", vector)
print("Matrix:\n", matrix)
print("Tensor:\n", tensor)

Scalar: tensor(9)
Vector: tensor([11, 22, 33])
Matrix:
 tensor([[11, 12],
        [13, 14]])
Tensor:
 tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])


## **Basic Tensor Operations**

In [3]:
# basic operations on tensors
x = torch.tensor([[1, 2], [3, 4]], dtype=torch.float32)
y = torch.tensor([[5, 6], [7, 8]], dtype=torch.float32)

print("Addition:\n", x + y)  # element-wise addition
print("Multiplication:\n", x * y)  # element-wise multiplication
print("Matrix Multiplication:\n", torch.matmul(x, y))

Addition:
 tensor([[ 6.,  8.],
        [10., 12.]])
Multiplication:
 tensor([[ 5., 12.],
        [21., 32.]])
Matrix Multiplication:
 tensor([[19., 22.],
        [43., 50.]])


## **Reshaping and Transposing**

In [4]:
# reshaping tensors
reshaped_tensor = tensor.view(2, 4)
print("Reshaped Tensor:\n", reshaped_tensor)

# transposing tensors
t_transposed = torch.transpose(x, 0, 1)
print("Transposed Tensor:\n", t_transposed)

Reshaped Tensor:
 tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])
Transposed Tensor:
 tensor([[1., 3.],
        [2., 4.]])


## **Advanced Tensor Operations**

In [5]:
# squeeze and unsqueeze tensor
t_squeezed = torch.squeeze(torch.tensor([[[1], [2], [3]]]))
print("Squeezed Tensor:\n", t_squeezed)

t_unsqueezed = torch.unsqueeze(torch.tensor([1, 2, 3]), dim=1)
print("Unsqueezed Tensor:\n", t_unsqueezed)

Squeezed Tensor:
 tensor([1, 2, 3])
Unsqueezed Tensor:
 tensor([[1],
        [2],
        [3]])


## **Permutation**

In [6]:
# permutation
z = torch.rand(2, 3, 4)
z_permuted = z.permute(2, 0, 1)
print("Permuted Tensor Shape:\n", z_permuted.shape)

Permuted Tensor Shape:
 torch.Size([4, 2, 3])


## **Exponentiation**

In [7]:
# element-wise exponentiation
t_exp = torch.pow(x, 2)
print("Element-wise exponentiation:\n", t_exp)

Element-wise exponentiation:
 tensor([[ 1.,  4.],
        [ 9., 16.]])


## **Einsum Operations**

In [8]:
# einsum examples
a = torch.tensor([[1, 2], [3, 4]])
b = torch.tensor([[5, 6], [7, 8]])

# element-wise multiplication
einsum_result1 = torch.einsum('ij,ij->ij', [a, b])
print("Einsum - Element-wise multiplication:\n", einsum_result1)

# matrix multiplication
einsum_result2 = torch.einsum('ik,kj->ij', [x, y])
print("Einsum - Matrix Multiplication:\n", einsum_result2)

# sum across columns
einsum_result3 = torch.einsum('ij->i', torch.tensor([[1, 2, 3], [4, 5, 6]]))
print("Einsum - Sum across columns:\n", einsum_result3)

Einsum - Element-wise multiplication:
 tensor([[ 5, 12],
        [21, 32]])
Einsum - Matrix Multiplication:
 tensor([[19., 22.],
        [43., 50.]])
Einsum - Sum across columns:
 tensor([ 6, 15])


## **Einops for Tensor Manipulations**

In [9]:
# using einops for tensor manipulations
# rearranging
z_rearranged = rearrange(z, 'b c h -> h b c')
print("Einops - Rearranged Tensor Shape:\n", z_rearranged.shape)

# reducing
z_reduced = reduce(z, 'b c h -> b h', 'sum')
print("Einops - Reduced Tensor Shape:\n", z_reduced.shape)

Einops - Rearranged Tensor Shape:
 torch.Size([4, 2, 3])
Einops - Reduced Tensor Shape:
 torch.Size([2, 4])
